service: my-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    MY_ENV_VAR: "some_value"
    ANOTHER_ENV_VAR: "another_value"

plugins:
  - serverless-step-functions
  - serverless-offline
  - serverless-step-functions-offline

functions:
  firstFunction:
    handler: dist/handler.firstFunction
    events:
      - http:
          path: first
          method: get

  secondFunction:
    handler: dist/handler.secondFunction

stepFunctions:
  stateMachines:
    myStateMachine:
      definition:
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:123456789012:function:firstFunction
            Next: SecondState
          SecondState:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:123456789012:function:secondFunction
            End: true

custom:
  serverless-offline:
    # Optional custom configuration for serverless-offline

  serverless-step-functions-offline:
    ENV_VARIABLES:
      MY_ENV_VAR: "some_value"
      ANOTHER_ENV_VAR: "another_value"
